<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9dxTEE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9dxTEE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9dxTEE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9dxTEE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX9dxTEE\App_KernelDevDebugContainer([
    'container.build_hash' => 'X9dxTEE',
    'container.build_id' => 'b7f6aa86',
    'container.build_time' => 1625607215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9dxTEE');
